### ISSUE TITLE
I failed to build because openssh-server wasn't installed

### ISSUE THREAD

**Issue by never-software** [sustainable-rails/sustainable-rails-dev#2]
Hello!

I managed to fix it by installing it and creating the below directory. I'm no expert at Docker so maybe this is just a me issue.

RUN apt-get update -yq && \
    apt-get install -y ca-certificates curl gnupg && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | \
       gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | \
       tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update -yq && \
    apt-get install nodejs -yq  && \
    npm install -g yarn && \
    apt-get install -yq openssh-server

RUN mkdir /var/run/sshd

**Comment by davetron5000** [comment]
There's nothing that requires an ssh server.  If you have a specific error that you encountered, post here and re-open, but I'm not going to add an ssh server to this dev image as there's no need to.

**Comment by modulistic** [comment]
`docker-compose.dx.yml` specifies `/usr/sbin/sshd -D` as the entrypoint for `sustainable-rails-dev`.

I think the intended entrypoint is `/root/show-help-in-app-container-then-wait.sh`.

I am opening a trivial merge request with a fix that assumes this.
